---
title: "第 1 章章末問題"
output: html_notebook
---

## 問題 1-1
変動係数：標準偏差を平均で割った値。平均が大きく違う2つのデータのばらつきを比較する際に使う。

```{r}
5.63/171.58 # 男性身長の変動係数
5.56/158.23 # 女性身長の変動係数
```

女性身長の標準偏差が小さいが、変動係数が大きいので女性の方が身長のばらつきが小さいと言えない。

## 問題 1-2

```{r}
x <- c(2, 5, 11, 7, 9)
mean(x) # 算術平均
prod(x)^(1/length(x)) # 幾何平均
1/mean(1/x) # 調和平均
var(x) # 不偏分散（R では不偏分散を標準分散として出力する）
sd(x) # 不偏分散平方根
```

## 問題 1-3
**平均偏差**
$$
\frac{1}{n}\sum^{n}_{j=1}|x_j-\overline{x}|
$$
**標準偏差**
$$
\sigma = \sqrt{\frac{1}{n}\sum^{n}_{j=1}(x_j-\overline{x})^2}
$$

```{r}
x <- c(34, 56, 32, 15, 49)
sum(abs(x-mean(x)))/length(x) # 平均偏差
sqrt(sum((x-mean(x))^2)/length(x)) # 標準偏差
```

## 問題 1-4

```{r}
a <- c(65, 59, 62)
b <- c(500, 750, 690)
sum(a*b)/sum(x)
```

## 問題 1-5

```{r}
height <- c(171.8, 167.2, 180.9)
weight <- c(74.4, 56.3, 93.2)
weight/(height/100)^2
```

## 問題 1-6

```{r}
x <- c(3, 4, 8, 11, 7)
sd(x) # 不偏分散の平方根
sqrt(sum((x-mean(x))^2)/length(x)) # 標準偏差
```

## 問題 1-7

$$
Z = \frac{x-\overline{x}}{\sigma}
$$
$$
偏差値=50+10Z
$$

```{r}
math <- scan(pipe("pbpaste"))
x <- sqrt(sum((math-mean(math))^2)/length(math))
50+10*((40-mean(math))/x)
50+10*((85-mean(math))/x)
```

## 問題 1-8

```{r}
x <- rnorm(100, 50, 10)
hist(x)
```

## 問題 1-9

```{r}
x <- rnorm(100, 50, 5)
y <- rnorm(100, 10, 10)
IQR(x)
IQR(y)
boxplot(x, y)
```

## 問題 1-10
```{r}
x <- rnorm(5, 170, 10)
y <- c(500, x)
mean(x)
median(x)
mean(y)
median(y)
```


## 問題 1-11

```{r}
sqrt(sum((x-mean(x))^2)/length(x))
mad(x)
sd(x)
sqrt(sum((y-mean(y))^2)/length(y))
mad(y)
sd(y)
```


## 問題 1-12
```{r}
sd_org = sqrt(sum((math-mean(math))^2)/length(math))
z = (math-mean(math))/sd_org
skewness <- mean(z^3)
kurtosis <- mean(z^4)-3
skewness
kurtosis
```

## 問題 1-13
$$
\begin{split}
{\sigma^2}&=\frac{1}{n}\sum^n_{j=1}(x_i-\overline{x})^2\\
&=\frac{1}{n}\sum^n_{j=1}({x_i}^2-2x_i\overline{x}+\overline{x}^2)\\
&={x_i}^2-\frac{2}{n}(n\overline{x}^2)+\overline{x}^2\\
&={x_i}^2-\overline{x}^2
\end{split}
$$

## 問題 1-14
